//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessCodingModelContex : DbContext
    {
        public BusinessCodingModelContex()
            : base("name=BusinessCodingModelContex")
        {
        }

        public BusinessCodingModelContex(string connectionString)
            : base(connectionString)
        {
        }

        public BusinessCodingModelContex(DbConnection connection)
            : base(connection, true)
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
        public DbSet<Companies> Companies { get; set; }
        public DbSet<Empolyees> Empolyees { get; set; }
        public DbSet<TypesOfEmployees> TypesOfEmployees { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<Descriptions> Descriptions { get; set; }
        public DbSet<TypesOfOffices> TypesOfOffices { get; set; }
    }
}
