//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Companies : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int companyID;
        private string name;
        private int respect;
        private double money;
        private double costOfLiving;
        private int typesOfOfficesTOOfficeID;
        private int userUserID;

        public int CompanyID 
        {
            get { return companyID; }
            set
            {
                companyID = value;
                OnPropertyChanged("CompanyID");
            }
        }

        public string Name 
        { 
            get { return name; } 
            set
            {
                name = value;
                OnPropertyChanged("Name");
            }
        }

        public int Respect 
        {
            get { return respect; }
            set
            {
                respect = value;
                OnPropertyChanged("Respect");
            }
        }

        public double Money 
        {
            get { return money; }
            set
            {
                money = value;
                OnPropertyChanged("Money");
            }
        }

        public double CostOfLiving 
        {
            get { return costOfLiving; }
            set 
            {
                costOfLiving = value;
                OnPropertyChanged("CostOfLiving");
            }
        }

        public int TypesOfOfficesTOOfficeID 
        {
            get { return typesOfOfficesTOOfficeID; }
            set
            {
                typesOfOfficesTOOfficeID = value;
                OnPropertyChanged("TypesOfOfficesTOOfficeID");
            }
        }
        
        public int UsersUserID 
        {
            get { return userUserID; }
            set
            {
                userUserID = value;
                OnPropertyChanged("UsersUserID");
            }
        }
    }
}
