//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Empolyees : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int employeeID;
        private Nullable<DateTime> dateOfHiring;
        private int typesOfEmployeesTOEmployeeID;
        private Nullable<int> companiesCompanyID;

        public int EmployeeID
        {
            get { return employeeID; }
            set
            {
                employeeID = value;
                OnPropertyChanged("EmployeeID");
            }

        }
        public Nullable<System.DateTime> DateOfHiring
        {
            get { return dateOfHiring; }
            set
            {
                dateOfHiring = value;
                OnPropertyChanged("DateOfHiring");
            }
        }

        public int TypesOfEmployeesTOEmployeeID
        {
            get { return typesOfEmployeesTOEmployeeID; }
            set
            {
                typesOfEmployeesTOEmployeeID = value;
                OnPropertyChanged("TypesOfEmployeesTOEmployeeID");
            }
        }

        public Nullable<int> CompaniesCompanyID
        {
            get { return companiesCompanyID; }
            set
            {
                companiesCompanyID = value;
                OnPropertyChanged("CompaniesCompanyID");
            }
        }
    }
}
