//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Projects : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int projectID;
        private string name;
        private short complexity;
        private short timeRounds;
        private Nullable<short> timeToEnd;
        private double gratification;
        private int minRespect;
        private short minCodity;
        private Nullable<int> companiesCompanyID;

        public int ProjectID 
        {
            get { return projectID; }
            set
            {
                projectID = value;
                OnPropertyChanged("ProjectID");
            }
        }

        public string Name 
        {
            get { return name; }
            set
            {
                name = value;
                OnPropertyChanged("Name");
            }
        }

        public short Complexity 
        {
            get { return complexity; }
            set
            {
                complexity = value;
                OnPropertyChanged("Complexity");
            }
        }

        public short TimeRounds 
        {
            get { return timeRounds; }
            set
            {
                timeRounds = value;
                OnPropertyChanged("TimeRounds");
            }
        }

        public Nullable<short> TimeToEnd 
        {
            get { return timeToEnd; }
            set
            {
                timeToEnd = value;
                OnPropertyChanged("TimeToEnd");
            }
        }

        public double Gratification 
        {
            get { return gratification; }
            set
            {
                gratification = value;
                OnPropertyChanged("Gratification");
            }
        }

        public int MinRespect 
        {
            get { return minRespect; }
            set
            {
                minRespect = value;
                OnPropertyChanged("MinRespect");
            }
        }

        public short MinCodity 
        {
            get { return minCodity; }
            set
            {
                minCodity = value;
                OnPropertyChanged("MinCodity");
            }
        }

        public Nullable<int> CompaniesCompanyID 
        {
            get { return companiesCompanyID; }
            set
            {
                companiesCompanyID = value;
                OnPropertyChanged("CompaniesCompanyID");
            }
        }
    }
}
