//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TypesOfEmployees : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int tOEmployeeID;
        private string name;
        private double salary;
        private short codity;

        public int TOEmployeeID
        {
            get { return tOEmployeeID; }
            set
            {
                tOEmployeeID = value;
                OnPropertyChanged("TOEmployeeID");
            }
        }

        public string Name
        {
            get { return name; }
            set
            {
                name = value;
                OnPropertyChanged("Name");
            }
        }

        public double Salary
        {
            get { return salary; }
            set
            {
                salary = value;
                OnPropertyChanged("Salary");
            }
        }

        public short Codity
        {
            get { return codity; }
            set
            {
                codity = value;
                OnPropertyChanged("Codity");
            }
        }
    }
}

