//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TypesOfOffices : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int tOOfficeID;
        private string name;
        private short capacity;
        private double costOfHiring;

        public int TOOfficeID
        {
            get
            {
                return tOOfficeID;
            }
            set
            {
                tOOfficeID = value;
                OnPropertyChanged("TOOfficeID");
            }
        }

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
                OnPropertyChanged("Name");
            }
        }

        public short Capacity
        {
            get
            {
                return capacity;
            }
            set
            {
                capacity = value;
                OnPropertyChanged("Value");
            }
        }

        public double CostOfHiring
        {
            get
            {
                return costOfHiring;
            }
            set
            {
                costOfHiring = value;
                OnPropertyChanged("CostOfHiring");
            }
        }
    }
}
