//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationPanel.DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Users : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        virtual protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        private int userID;
        private string login;
        private string password;
        private string email;
        private DateTime activationDate;
        private DateTime lastLogin;

        public int UserID
        {
            get { return userID; }
            set
            {
                userID = value;
                OnPropertyChanged("Value");
            }
        }

        public string Login
        {
            get { return login; }
            set
            {
                login = value;
                OnPropertyChanged("Login");
            }
        }

        public string Password
        {
            get { return password; }
            set
            {
                password = value;
                OnPropertyChanged("Password");
            }
        }

        public string Email
        {
            get { return email; }
            set
            {
                email = value;
            }
        }

        public System.DateTime ActivationDate
        {
            get { return activationDate; }
            set
            {
                activationDate = value;
                OnPropertyChanged("ActivationDate");
            }
        }

        public System.DateTime LastLogin
        {
            get { return lastLogin; }
            set
            {
                lastLogin = value;
                OnPropertyChanged("LastLogin");
            }
        }
    }
}
